/**
 * datos-simulados.ts
 * Catálogo de perfumes de demostración para desarrollo local.
 * Se reemplaza por la API real cuando el backend esté conectado a Supabase.
 */
import type { Perfume } from '../tipos/Perfume.tipos';

export const PERFUMES_SIMULADOS: Perfume[] = [
  // ─── NICHO ────────────────────────────────────────────────────────
  {
    id: 'nicho-01',
    nombre: 'Layton',
    marcaId: 'marca-pdm',
    marca: { id: 'marca-pdm', nombre: 'Parfums de Marly' },
    clasificacion: 'Nicho',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 125,
    familiaOlfativa: 'Oriental',
    descripcion: 'Una fragancia icónica que combina manzana verde, lavanda y especias con una base vainillada y amaderada de extraordinaria sofisticación.',
    imagenUrl: null,
    precioVentaCrc: 185000,
    stockProveedor: true,
  },
  {
    id: 'nicho-02',
    nombre: 'Pegasus',
    marcaId: 'marca-pdm',
    marca: { id: 'marca-pdm', nombre: 'Parfums de Marly' },
    clasificacion: 'Nicho',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 125,
    familiaOlfativa: 'Amaderado',
    descripcion: 'Una oda a la caballería real. Almendra, lavanda y vainilla se funden en un acorde irresistible de elegancia ecuestre.',
    imagenUrl: null,
    precioVentaCrc: 175000,
    stockProveedor: true,
  },
  {
    id: 'nicho-03',
    nombre: 'Waves of Success',
    marcaId: 'marca-xerjoff',
    marca: { id: 'marca-xerjoff', nombre: 'Xerjoff' },
    clasificacion: 'Nicho',
    genero: 'Unisex',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    descripcion: 'Bergamota siciliana y rosa damascena sobre un fondo de sándalo y almizcle. La definición italiana del lujo olfativo.',
    imagenUrl: null,
    precioVentaCrc: 220000,
    stockProveedor: true,
  },
  {
    id: 'nicho-04',
    nombre: 'Interlude Man',
    marcaId: 'marca-amouage',
    marca: { id: 'marca-amouage', nombre: 'Amouage' },
    clasificacion: 'Nicho',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Una sinfonía olfativa de incienso, orégano y ámbar. Narrativa de conflicto y resolución expresada en perfume.',
    imagenUrl: null,
    precioVentaCrc: 245000,
    stockProveedor: true,
  },
  {
    id: 'nicho-05',
    nombre: 'Feminité du Bois',
    marcaId: 'marca-serge',
    marca: { id: 'marca-serge', nombre: 'Serge Lutens' },
    clasificacion: 'Nicho',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 50,
    familiaOlfativa: 'Amaderado',
    descripcion: 'El sándalo de Mysore se viste de ciruela y canela en esta joya atemporal que redefinió la perfumería moderna.',
    imagenUrl: null,
    precioVentaCrc: 155000,
    stockProveedor: true,
  },
  {
    id: 'nicho-06',
    nombre: 'Eau Duelle',
    marcaId: 'marca-diptyque',
    marca: { id: 'marca-diptyque', nombre: 'Diptyque' },
    clasificacion: 'Nicho',
    genero: 'Unisex',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Vainilla líquida y pimienta negra. Un dúo perfecto entre calidez y frescor que seduce desde el primer instante.',
    imagenUrl: null,
    precioVentaCrc: 145000,
    stockProveedor: true,
  },

  // ─── ÁRABE ────────────────────────────────────────────────────────
  {
    id: 'arabe-01',
    nombre: 'Khamrah',
    marcaId: 'marca-lattafa',
    marca: { id: 'marca-lattafa', nombre: 'Lattafa' },
    clasificacion: 'Arabe',
    genero: 'Unisex',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Un festín olfativo de whisky, vainilla y oud. Profundo, ardiente y adictivo. El secreto de las mil y una noches.',
    imagenUrl: null,
    precioVentaCrc: 55000,
    stockProveedor: true,
  },
  {
    id: 'arabe-02',
    nombre: 'Oud Mood',
    marcaId: 'marca-lattafa',
    marca: { id: 'marca-lattafa', nombre: 'Lattafa' },
    clasificacion: 'Arabe',
    genero: 'Unisex',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    descripcion: 'Oud puro del Medio Oriente fusionado con rosa y almizcle. Una fragancia que transporta al corazón de Arabia.',
    imagenUrl: null,
    precioVentaCrc: 48000,
    stockProveedor: true,
  },
  {
    id: 'arabe-03',
    nombre: 'Rose Oud',
    marcaId: 'marca-arabian',
    marca: { id: 'marca-arabian', nombre: 'Arabian Oud' },
    clasificacion: 'Arabe',
    genero: 'Unisex',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    descripcion: 'La reina de las flores árabe. Rosa de Taif y oud del bosque se unen en una danza inmortal de belleza y misterio.',
    imagenUrl: null,
    precioVentaCrc: 72000,
    stockProveedor: true,
  },
  {
    id: 'arabe-04',
    nombre: 'Dahn Al Oudh Moattaq',
    marcaId: 'marca-ajmal',
    marca: { id: 'marca-ajmal', nombre: 'Ajmal' },
    clasificacion: 'Arabe',
    genero: 'Masculino',
    concentracion: 'Parfum',
    volumenMl: 6,
    familiaOlfativa: 'Amaderado',
    descripcion: 'Aceite de oud puro, sin mezclas. La esencia más pura del árbol de agarwood, reservada para los conocedores.',
    imagenUrl: null,
    precioVentaCrc: 95000,
    stockProveedor: true,
  },
  {
    id: 'arabe-05',
    nombre: 'Madinah',
    marcaId: 'marca-alharamain',
    marca: { id: 'marca-alharamain', nombre: 'Al Haramain' },
    clasificacion: 'Arabe',
    genero: 'Unisex',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Incienso, ámbar y una pizca de especias del bazar. La fragancia de la ciudad sagrada, ahora en tu piel.',
    imagenUrl: null,
    precioVentaCrc: 62000,
    stockProveedor: true,
  },

  // ─── DISEÑADOR ────────────────────────────────────────────────────
  {
    id: 'dis-01',
    nombre: 'Eros',
    marcaId: 'marca-versace',
    marca: { id: 'marca-versace', nombre: 'Versace' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    descripcion: 'Menta fresca, manzana verde y limón siciliano. La fragancia del dios griego del amor reinterpretada por Donatella.',
    imagenUrl: null,
    precioVentaCrc: 65000,
    stockProveedor: true,
  },
  {
    id: 'dis-02',
    nombre: 'L\'Interdit',
    marcaId: 'marca-givenchy',
    marca: { id: 'marca-givenchy', nombre: 'Givenchy' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 80,
    familiaOlfativa: 'Floral',
    descripcion: 'Azahar blanco y vetiver negro. La dualidad entre inocencia y transgresión en un frasco icónico de la moda parisina.',
    imagenUrl: null,
    precioVentaCrc: 82000,
    stockProveedor: true,
  },
  {
    id: 'dis-03',
    nombre: 'Sauvage EDP',
    marcaId: 'marca-dior',
    marca: { id: 'marca-dior', nombre: 'Dior' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    descripcion: 'Bergamota calabresa y ambroxan. La fragancia más vendida del mundo: cruda, noble y deslumbrante como el desierto al amanecer.',
    imagenUrl: null,
    precioVentaCrc: 92000,
    stockProveedor: true,
  },
  {
    id: 'dis-04',
    nombre: 'Bleu de Chanel EDP',
    marcaId: 'marca-chanel',
    marca: { id: 'marca-chanel', nombre: 'Chanel' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    descripcion: 'Incienso, madera de sándalo y cedro. La quintaesencia del hombre moderno según el lenguaje eterno de Chanel.',
    imagenUrl: null,
    precioVentaCrc: 105000,
    stockProveedor: true,
  },
  {
    id: 'dis-05',
    nombre: 'Acqua di Giò Profondo',
    marcaId: 'marca-armani',
    marca: { id: 'marca-armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 125,
    familiaOlfativa: 'Acuático',
    descripcion: 'Mineral, azul profundo y misterioso. La esencia del Mediterráneo capturada en su versión más oscura e hipnótica.',
    imagenUrl: null,
    precioVentaCrc: 88000,
    stockProveedor: true,
  },
  {
    id: 'dis-06',
    nombre: 'CK One',
    marcaId: 'marca-ck',
    marca: { id: 'marca-ck', nombre: 'Calvin Klein' },
    clasificacion: 'Diseñador',
    genero: 'Unisex',
    concentracion: 'EDT',
    volumenMl: 200,
    familiaOlfativa: 'Fresco',
    descripcion: 'Té verde, bergamota y almizcle blanco. El pionero del unisex moderno, una revolución olfativa que sigue vigente.',
    imagenUrl: null,
    precioVentaCrc: 52000,
    stockProveedor: true,
  },
];
