// Sugerencia de destacados (sin aplicar, curación pendiente del dueño): Dior Sauvage, Bleu de Chanel, Coco Mademoiselle, YSL Libre, Giorgio Armani My Way, Lattafa Khamrah Dukhan, Rasasi Hawas.
import type { Perfume } from './Perfume.tipos';

export const CATALOGO_PERFUMES: Perfume[] = [
  // ─── MUJER ──────────────────────────────────────────────
  {
    id: 'p-01',
    nombre: 'Ambassador Pink',
    marcaId: 'gisada',
    marca: { id: 'gisada', nombre: 'Gisada' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-120327.png',
    precioVentaCrc: 37500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Floral', intensidad: 85 }, { nombre: 'Dulce', intensidad: 70 }, { nombre: 'Almizclado', intensidad: 55 }, { nombre: 'Vainilla', intensidad: 40 }],
    notas: {
      salida: ['Albaricoque', 'Pera', 'Bergamota', 'Hojas de violeta'],
      corazon: ['Ciruela', 'Nardos', 'Frambuesa', 'Rosa'],
      fondo: ['Vainilla', 'Haba tonka', 'Pachulí', 'Sándalo'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-02',
    nombre: 'My Way (Recharge)',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'Parfum',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9972-247x247.png',
    precioVentaCrc: 61000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Dulce', intensidad: 80 }, { nombre: 'Almizclado', intensidad: 65 }, { nombre: 'Cítrico', intensidad: 50 }, { nombre: 'Vainilla', intensidad: 40 }],
    notas: {
      salida: ['Flor de azahar del naranjo', 'Naranja amarga', 'Bergamota'],
      corazon: ['Iris Pallida', 'Nardo de la India', 'Ambreta'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-03',
    nombre: 'My Way Floral',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-143707-247x247.jpg',
    precioVentaCrc: 50500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 75 }, { nombre: 'Dulce', intensidad: 60 }, { nombre: 'Almizclado', intensidad: 45 }, { nombre: 'Verde', intensidad: 35 }],
    notas: {
      salida: ['Flor de azahar del naranjo', 'Mandarina verde', 'Naranja amarga'],
      corazon: ['Nardo de la India', 'Neroli'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-04',
    nombre: 'Daisy Wild Eau So Extra',
    marcaId: 'marc-jacobs',
    marca: { id: 'marc-jacobs', nombre: 'Marc Jacobs' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-165837.png',
    precioVentaCrc: 50500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Floral', intensidad: 85 }, { nombre: 'Dulce', intensidad: 70 }, { nombre: 'Gourmand', intensidad: 55 }, { nombre: 'Vainilla', intensidad: 40 }],
    notas: {
      salida: ['Flor de plátano', 'Pera', 'Bergamota'],
      corazon: ['Margarita de chocolate', 'Jazmín'],
      fondo: ['Vainilla', 'Ámbar', 'Sándalo'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-05',
    nombre: 'Paradoxe Virtual Flower',
    marcaId: 'prada',
    marca: { id: 'prada', nombre: 'Prada' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-122328.png',
    precioVentaCrc: 58000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Almizclado', intensidad: 65 }, { nombre: 'Ámbar', intensidad: 45 }, { nombre: 'Fresco', intensidad: 35 }],
    notas: {
      salida: ['Bergamota italiana', 'Cítricos'],
      corazon: ['Jazmín', 'Neroli'],
      fondo: ['Almizcle', 'Semillas de ambreta'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-06',
    nombre: 'Seductive',
    marcaId: 'guess',
    marca: { id: 'guess', nombre: 'Guess' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-27-153727-247x247.png',
    precioVentaCrc: 13500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Frutal', intensidad: 80 }, { nombre: 'Dulce', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 45 }, { nombre: 'Especiado', intensidad: 35 }],
    notas: {
      salida: ['Pera', 'Bergamota', 'Grosellas negras'],
      corazon: ['Flor de azahar del naranjo', 'Jazmín', 'Raíz de lirio'],
      fondo: ['Vainilla', 'Madera de cachemira', 'Incienso de olíbano'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-07',
    nombre: '9 PM Mujer',
    marcaId: 'afnan',
    marca: { id: 'afnan', nombre: 'Afnan' },
    clasificacion: 'Arabe',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/629017072607-247x247.jpg',
    precioVentaCrc: 19500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Floral', intensidad: 85 }, { nombre: 'Oriental', intensidad: 70 }, { nombre: 'Amaderado', intensidad: 55 }, { nombre: 'Especiado', intensidad: 40 }],
    notas: {
      salida: ['Frambuesa', 'Manzana', 'Naranja', 'Violeta'],
      corazon: ['Rosa', 'Iris', 'Peonía', 'Jazmín'],
      fondo: ['Ámbar', 'Cedro', 'Ciprés', 'Pino'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-08',
    nombre: 'Hawas Reina',
    marcaId: 'rasasi',
    marca: { id: 'rasasi', nombre: 'Rasasi' },
    clasificacion: 'Arabe',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-161632.jpg',
    precioVentaCrc: 22500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Floral', intensidad: 80 }, { nombre: 'Dulce', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 50 }, { nombre: 'Verde', intensidad: 35 }],
    notas: {
      salida: ['Granada', 'Manzana', 'Toronja'],
      corazon: ['Jazmín sambac', 'Iris', 'Cítricos'],
      fondo: ['Praliné', 'Pachulí', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-09',
    nombre: 'La Vida Es Bella (Estuche 2 piezas)',
    marcaId: 'lancome',
    marca: { id: 'lancome', nombre: 'Lancôme' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    descripcion: 'Set de regalo, 2 piezas.',
    imagenUrl: null,
    precioVentaCrc: 76000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Dulce', intensidad: 100 }, { nombre: 'Gourmand', intensidad: 85 }, { nombre: 'Floral', intensidad: 70 }, { nombre: 'Almizclado', intensidad: 55 }, { nombre: 'Frutal', intensidad: 40 }],
    notas: {
      salida: ['Grosellas negras', 'Pera'],
      corazon: ['Iris', 'Jazmín', 'Flor de azahar del naranjo'],
      fondo: ['Praliné', 'Vainilla', 'Pachulí', 'Haba tonka'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-10',
    nombre: 'La Vida Es Bella',
    marcaId: 'lancome',
    marca: { id: 'lancome', nombre: 'Lancôme' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 62500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Dulce', intensidad: 100 }, { nombre: 'Gourmand', intensidad: 85 }, { nombre: 'Floral', intensidad: 70 }, { nombre: 'Almizclado', intensidad: 55 }, { nombre: 'Frutal', intensidad: 40 }],
    notas: {
      salida: ['Grosellas negras', 'Pera'],
      corazon: ['Iris', 'Jazmín', 'Flor de azahar del naranjo'],
      fondo: ['Praliné', 'Vainilla', 'Pachulí', 'Haba tonka'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-11',
    nombre: 'Divine Mujer (Edición Colección)',
    marcaId: 'jean-paul',
    marca: { id: 'jean-paul', nombre: 'Jean Paul' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: null,
    precioVentaCrc: 55500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Frutal', intensidad: 80 }, { nombre: 'Dulce', intensidad: 65 }, { nombre: 'Almizclado', intensidad: 50 }, { nombre: 'Especiado', intensidad: 35 }],
    notas: {
      salida: ['Calipsone', 'Bayas rojas', 'Bergamota'],
      corazon: ['Azucena', 'Ylang-ylang', 'Jazmín'],
      fondo: ['Merengue', 'Almizcle', 'Pachulí'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-12',
    nombre: 'Divine Mujer (Estuche 3 piezas)',
    marcaId: 'jean-paul',
    marca: { id: 'jean-paul', nombre: 'Jean Paul' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    descripcion: 'Set de regalo, 3 piezas.',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/jean-paul-gaultier-ladies-divine-gift-set-fragrances-8435415103169.jpg',
    precioVentaCrc: 71000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Frutal', intensidad: 80 }, { nombre: 'Dulce', intensidad: 65 }, { nombre: 'Almizclado', intensidad: 50 }, { nombre: 'Especiado', intensidad: 35 }],
    notas: {
      salida: ['Calipsone', 'Bayas rojas', 'Bergamota'],
      corazon: ['Azucena', 'Ylang-ylang', 'Jazmín'],
      fondo: ['Merengue', 'Almizcle', 'Pachulí'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-13',
    nombre: 'Libre Berry Crush',
    marcaId: 'ysl',
    marca: { id: 'ysl', nombre: 'Yves Saint Laurent' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-24-121023.png',
    precioVentaCrc: 74500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Floral', intensidad: 80 }, { nombre: 'Aromático', intensidad: 65 }, { nombre: 'Dulce', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Frambuesa', 'Mandarina'],
      corazon: ['Flor de azahar del naranjo', 'Lavanda'],
      fondo: ['Vainilla Bourbon', 'Coco', 'Almizcle'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-14',
    nombre: 'My Way',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3614272907690.jpg',
    precioVentaCrc: 59000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 75 }, { nombre: 'Dulce', intensidad: 60 }, { nombre: 'Almizclado', intensidad: 45 }, { nombre: 'Vainilla', intensidad: 35 }],
    notas: {
      salida: ['Flor de azahar del naranjo', 'Bergamota'],
      corazon: ['Nardo de la India', 'Jazmín de la India'],
      fondo: ['Vainilla de Madagascar', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-15',
    nombre: 'My Way Nectar',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 62500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Dulce', intensidad: 100 }, { nombre: 'Floral', intensidad: 85 }, { nombre: 'Gourmand', intensidad: 70 }, { nombre: 'Almizclado', intensidad: 55 }, { nombre: 'Vainilla', intensidad: 40 }],
    notas: {
      salida: ['Pera', 'Flor de azahar del naranjo', 'Bergamota'],
      corazon: ['Nardos', 'Jazmín', 'Hojas de violeta'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-16',
    nombre: "L'Imperatrice",
    marcaId: 'dolce-gabbana',
    marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 19500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Frutal', intensidad: 85 }, { nombre: 'Floral', intensidad: 65 }, { nombre: 'Verde', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Kiwi', 'Ruibarbo', 'Pimienta rosa'],
      corazon: ['Sandía', 'Ciclamen', 'Jazmín'],
      fondo: ['Limonero', 'Almizcle', 'Sándalo'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-17',
    nombre: 'Halloween Tradicional',
    marcaId: 'jesus-del-pozo',
    marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/8431754342016.jpg',
    precioVentaCrc: 17000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Oriental', intensidad: 80 }, { nombre: 'Especiado', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 50 }, { nombre: 'Ámbar', intensidad: 40 }],
    notas: {
      salida: ['Violeta', 'Notas marinas', 'Hoja de plátano', 'Petitgrain'],
      corazon: ['Violeta', 'Magnolia', 'Lirio de los valles', 'Pimienta'],
      fondo: ['Incienso', 'Vainilla de Madagascar', 'Sándalo', 'Mirra'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-18',
    nombre: 'Acqua Di Parisis',
    marcaId: 'reyane',
    marca: { id: 'reyane', nombre: 'Reyane Tradition' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 11500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Floral', intensidad: 75 }, { nombre: 'Cítrico', intensidad: 60 }, { nombre: 'Fresco', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Notas marinas', 'Bergamota', 'Mandarina'],
      corazon: ['Muguet', 'Jazmín', 'Flor de loto'],
      fondo: ['Almizcle', 'Madera a la deriva', 'Ámbar'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-19',
    nombre: 'Halloween Blue Drop',
    marcaId: 'jesus-del-pozo',
    marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 19500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Verde', intensidad: 60 }, { nombre: 'Floral', intensidad: 45 }, { nombre: 'Almizclado', intensidad: 30 }],
    notas: {
      salida: ['Cítricos', 'Manzana verde', 'Lavanda'],
      corazon: ['Flores blancas', 'Jazmín', 'Violeta'],
      fondo: ['Almizcle', 'Cedro', 'Ámbar', 'Especias'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-20',
    nombre: 'Curve Chill Mujer',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Fresco', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Verde', intensidad: 65 }, { nombre: 'Acuático', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Té verde', 'Jengibre', 'Limón'],
      corazon: ['Peonía', 'Fresia', 'Guisante de olor'],
      fondo: ['Almizcle', 'Cedro', 'Vetiver'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-21',
    nombre: 'Tommy Girl',
    marcaId: 'tommy-hilfiger',
    marca: { id: 'tommy-hilfiger', nombre: 'Tommy Hilfiger' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 14500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Floral', intensidad: 80 }, { nombre: 'Fresco', intensidad: 65 }, { nombre: 'Frutal', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Manzano en flor', 'Camelia', 'Mandarina', 'Grosellas negras'],
      corazon: ['Limón', 'Madreselva', 'Rosa', 'Lirio'],
      fondo: ['Magnolia', 'Cedro', 'Sándalo', 'Jazmín'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-22',
    nombre: 'Thank U, Next',
    marcaId: 'ariana-grande',
    marca: { id: 'ariana-grande', nombre: 'Ariana Grande' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 23500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Dulce', intensidad: 85 }, { nombre: 'Gourmand', intensidad: 70 }, { nombre: 'Floral', intensidad: 55 }, { nombre: 'Almizclado', intensidad: 40 }],
    notas: {
      salida: ['Pera blanca', 'Frambuesa'],
      corazon: ['Crema de coco', 'Rosa rosada'],
      fondo: ['Macarrones dulces', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-23',
    nombre: 'Happy Mujer',
    marcaId: 'clinique',
    marca: { id: 'clinique', nombre: 'Clinique' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 21000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Floral', intensidad: 80 }, { nombre: 'Fresco', intensidad: 65 }, { nombre: 'Frutal', intensidad: 45 }, { nombre: 'Verde', intensidad: 30 }],
    notas: {
      salida: ['Naranja', 'Toronja sanguina', 'Mandarina', 'Bergamota'],
      corazon: ['Lirio de los valles', 'Fresia', 'Orquídea', 'Rosa'],
      fondo: ['Mimosa', 'Azucena', 'Magnolia', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-24',
    nombre: 'Fantasy Tradicional',
    marcaId: 'britney-spears',
    marca: { id: 'britney-spears', nombre: 'Britney Spears' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/719346065405.jpg',
    precioVentaCrc: 13000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Frutal', intensidad: 100 }, { nombre: 'Dulce', intensidad: 85 }, { nombre: 'Gourmand', intensidad: 70 }, { nombre: 'Floral', intensidad: 50 }, { nombre: 'Amaderado', intensidad: 35 }],
    notas: {
      salida: ['Kiwi', 'Lichi rojo', 'Membrillo'],
      corazon: ['Chocolate blanco', 'Quequito', 'Orquídea', 'Jazmín'],
      fondo: ['Almizcle', 'Raíz de lirio', 'Notas amaderadas'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-25',
    nombre: 'Curve Crush Mujer',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: null,
    precioVentaCrc: 13000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Dulce', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Gourmand', intensidad: 65 }, { nombre: 'Cítrico', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Cítricos', 'Té floral', 'Jengibre'],
      corazon: ['Leche', 'Canela', 'Cardamomo', 'Orquídea'],
      fondo: ['Vainilla', 'Azúcar', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-26',
    nombre: 'Ari',
    marcaId: 'ariana-grande',
    marca: { id: 'ariana-grande', nombre: 'Ariana Grande' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/812256020301-247x247.jpg',
    precioVentaCrc: 21000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Dulce', intensidad: 100 }, { nombre: 'Frutal', intensidad: 85 }, { nombre: 'Gourmand', intensidad: 70 }, { nombre: 'Floral', intensidad: 55 }, { nombre: 'Almizclado', intensidad: 40 }],
    notas: {
      salida: ['Frambuesa', 'Pera', 'Toronja'],
      corazon: ['Orquídea de vainilla', 'Lirio de los valles', 'Rosa'],
      fondo: ['Malvavisco', 'Almizcle', 'Notas amaderadas'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-34',
    nombre: '212 Tradicional Mujer',
    marcaId: 'carolina-herrera',
    marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 41500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Floral', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Fresco', intensidad: 65 }, { nombre: 'Almizclado', intensidad: 50 }, { nombre: 'Frutal', intensidad: 35 }],
    notas: {
      salida: ['Flor de azahar del naranjo', 'Flor de cactus', 'Mandarina', 'Bergamota'],
      corazon: ['Azucena', 'Gardenia', 'Fresia', 'Jazmín'],
      fondo: ['Almizcle', 'Sándalo'],
    },
    duracion: 4,
    proyeccion: 3,
  },

  // ─── HOMBRE ─────────────────────────────────────────────
  {
    id: 'p-27',
    nombre: 'In Motion (Tester)',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3616301623328.jpg',
    precioVentaCrc: 14500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Amaderado', intensidad: 65 }, { nombre: 'Fresco', intensidad: 50 }, { nombre: 'Cítrico', intensidad: 35 }],
    notas: {
      salida: ['Naranja', 'Albahaca', 'Hojas de violeta', 'Bergamota'],
      corazon: ['Nuez moscada', 'Canela', 'Pimienta rosa', 'Cardamomo'],
      fondo: ['Sándalo', 'Vetiver', 'Notas amaderadas', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-28',
    nombre: 'Voyage',
    marcaId: 'nautica',
    marca: { id: 'nautica', nombre: 'Nautica' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 8500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Verde', intensidad: 80 }, { nombre: 'Fresco', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 45 }, { nombre: 'Cítrico', intensidad: 30 }],
    notas: {
      salida: ['Manzana verde', 'Hojas verdes'],
      corazon: ['Flor de loto', 'Mimosa'],
      fondo: ['Almizcle', 'Cedro', 'Musgo de roble', 'Ámbar'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-29',
    nombre: 'CK One',
    marcaId: 'calvin-klein',
    marca: { id: 'calvin-klein', nombre: 'Calvin Klein' },
    clasificacion: 'Diseñador',
    genero: 'Unisex',
    concentracion: 'EDT',
    volumenMl: 200,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 17500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Fresco', intensidad: 85 }, { nombre: 'Acuático', intensidad: 65 }, { nombre: 'Verde', intensidad: 50 }, { nombre: 'Almizclado', intensidad: 35 }],
    notas: {
      salida: ['Limón', 'Bergamota', 'Mandarina', 'Piña', 'Cardamomo'],
      corazon: ['Lirio de los valles', 'Jazmín', 'Violeta', 'Nuez moscada'],
      fondo: ['Almizcle', 'Cedro', 'Sándalo', 'Musgo de roble', 'Ámbar'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-30',
    nombre: 'Bottled Beyond',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 150,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-102408-1.png',
    precioVentaCrc: 54000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Amaderado', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Cítrico', intensidad: 60 }, { nombre: 'Cuero', intensidad: 45 }, { nombre: 'Ámbar', intensidad: 35 }],
    notas: {
      salida: ['Jengibre', 'Notas cítricas'],
      corazon: ['Cuero', 'Acorde especiado'],
      fondo: ['Notas amaderadas', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-31',
    nombre: "L'Homme",
    marcaId: 'ysl',
    marca: { id: 'ysl', nombre: 'Yves Saint Laurent' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-101211-247x247.png',
    precioVentaCrc: 61500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Amaderado', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Aromático', intensidad: 65 }, { nombre: 'Almizclado', intensidad: 50 }, { nombre: 'Especiado', intensidad: 35 }],
    notas: {
      salida: ['Naranja amarga', 'Bergamota'],
      corazon: ['Vetiver', 'Lavanda', 'Geranio'],
      fondo: ['Madera de roble', 'Cedro'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-32',
    nombre: 'The Most Wanted (Tester)',
    marcaId: 'azzaro',
    marca: { id: 'azzaro', nombre: 'Azzaro' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Parfum',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.',
    imagenUrl: null,
    precioVentaCrc: 40000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Especiado', intensidad: 100 }, { nombre: 'Dulce', intensidad: 80 }, { nombre: 'Ámbar', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 50 }, { nombre: 'Vainilla', intensidad: 35 }],
    notas: {
      salida: ['Jengibre rojo', 'Cardamomo'],
      corazon: ['Maderas incandescentes', 'Caramelo'],
      fondo: ['Vainilla Bourbon', 'Vetiver'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-33',
    nombre: 'Uomo Born In Roma Purple Melancholia',
    marcaId: 'valentino',
    marca: { id: 'valentino', nombre: 'Valentino' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-173652-247x247.jpg',
    precioVentaCrc: 64000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Aromático', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Amaderado', intensidad: 65 }, { nombre: 'Ámbar', intensidad: 50 }, { nombre: 'Dulce', intensidad: 35 }],
    notas: {
      salida: ['Cardamomo', 'Pimienta'],
      corazon: ['Lavanda', 'Coco cremoso'],
      fondo: ['Maderas ambaradas', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-35',
    nombre: 'Light Blue Hombre',
    marcaId: 'dolce-gabbana',
    marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 125,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 33000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Amaderado', intensidad: 75 }, { nombre: 'Acuático', intensidad: 60 }, { nombre: 'Fresco', intensidad: 45 }, { nombre: 'Especiado', intensidad: 30 }],
    notas: {
      salida: ['Toronja', 'Bergamota', 'Mandarina siciliana', 'Enebro'],
      corazon: ['Pimienta', 'Romero', 'Palo de rosa'],
      fondo: ['Almizcle', 'Incienso', 'Musgo de roble'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-36',
    nombre: 'In Motion',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/737052852034.jpg',
    precioVentaCrc: 16500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Amaderado', intensidad: 65 }, { nombre: 'Fresco', intensidad: 50 }, { nombre: 'Cítrico', intensidad: 35 }],
    notas: {
      salida: ['Naranja', 'Albahaca', 'Hojas de violeta', 'Bergamota'],
      corazon: ['Nuez moscada', 'Canela', 'Pimienta rosa', 'Cardamomo'],
      fondo: ['Sándalo', 'Vetiver', 'Notas amaderadas', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-37',
    nombre: 'Club De Nuit Intense',
    marcaId: 'armaf',
    marca: { id: 'armaf', nombre: 'Armaf' },
    clasificacion: 'Arabe',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 105,
    familiaOlfativa: 'Amaderado',
    imagenUrl: null,
    precioVentaCrc: 17000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Frutal', intensidad: 85 }, { nombre: 'Amaderado', intensidad: 70 }, { nombre: 'Ámbar', intensidad: 55 }, { nombre: 'Almizclado', intensidad: 40 }],
    notas: {
      salida: ['Limón', 'Piña', 'Grosellas negras', 'Bergamota', 'Manzana'],
      corazon: ['Abedul', 'Jazmín', 'Rosa'],
      fondo: ['Almizcle', 'Ámbar gris', 'Pachulí', 'Vainilla'],
    },
    duracion: 5,
    proyeccion: 5,
  },
  {
    id: 'p-38',
    nombre: '9 PM Hombre',
    marcaId: 'afnan',
    marca: { id: 'afnan', nombre: 'Afnan' },
    clasificacion: 'Arabe',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: null,
    precioVentaCrc: 14500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Oriental', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Dulce', intensidad: 65 }, { nombre: 'Amaderado', intensidad: 50 }, { nombre: 'Ámbar', intensidad: 35 }],
    notas: {
      salida: ['Manzana', 'Canela', 'Lavanda silvestre', 'Bergamota'],
      corazon: ['Flor de azahar del naranjo', 'Lirio de los valles'],
      fondo: ['Vainilla', 'Haba tonka', 'Ámbar', 'Pachulí'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-39',
    nombre: '360 Red',
    marcaId: 'perry-ellis',
    marca: { id: 'perry-ellis', nombre: 'Perry Ellis' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/844061000551.jpg',
    precioVentaCrc: 14500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Amaderado', intensidad: 100 }, { nombre: 'Especiado', intensidad: 80 }, { nombre: 'Cítrico', intensidad: 60 }, { nombre: 'Aromático', intensidad: 45 }, { nombre: 'Almizclado', intensidad: 30 }],
    notas: {
      salida: ['Lima', 'Bergamota', 'Canela', 'Nuez moscada', 'Mandarina'],
      corazon: ['Lavanda', 'Cilantro'],
      fondo: ['Almizcle', 'Pachulí', 'Sándalo', 'Cedro rojo', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-40',
    nombre: 'Blue',
    marcaId: 'nautica',
    marca: { id: 'nautica', nombre: 'Nautica' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3412242508027-247x247.jpg',
    precioVentaCrc: 8500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Acuático', intensidad: 100 }, { nombre: 'Frutal', intensidad: 75 }, { nombre: 'Floral', intensidad: 55 }, { nombre: 'Amaderado', intensidad: 40 }, { nombre: 'Fresco', intensidad: 30 }],
    notas: {
      salida: ['Piña', 'Bergamota', 'Durazno'],
      corazon: ['Lirio de agua', 'Jazmín'],
      fondo: ['Sándalo', 'Cedro', 'Almizcle'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-41',
    nombre: 'Curve Chill Hombre',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Colonia',
    volumenMl: 125,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Fresco', intensidad: 100 }, { nombre: 'Cítrico', intensidad: 80 }, { nombre: 'Aromático', intensidad: 60 }, { nombre: 'Amaderado', intensidad: 45 }, { nombre: 'Almizclado', intensidad: 30 }],
    notas: {
      salida: ['Aldehídos', 'Lima', 'Bergamota'],
      corazon: ['Té verde', 'Violeta', 'Pimienta blanca'],
      fondo: ['Sándalo', 'Almizcle', 'Vetiver', 'Cardamomo'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-42',
    nombre: 'Toy Boy',
    marcaId: 'moschino',
    marca: { id: 'moschino', nombre: 'Moschino' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/s-l1200-1-3.jpg',
    precioVentaCrc: 28000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Especiado', intensidad: 100 }, { nombre: 'Floral', intensidad: 80 }, { nombre: 'Amaderado', intensidad: 65 }, { nombre: 'Ámbar', intensidad: 50 }, { nombre: 'Dulce', intensidad: 35 }],
    notas: {
      salida: ['Pimienta rosa', 'Pera', 'Nuez moscada', 'Bergamota'],
      corazon: ['Rosa', 'Clavo de olor', 'Magnolia'],
      fondo: ['Madera de cachemira', 'Vetiver', 'Sándalo', 'Ámbar'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-43',
    nombre: 'Curve Connect Hombre',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Colonia',
    volumenMl: 125,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Especiado', intensidad: 100 }, { nombre: 'Frutal', intensidad: 80 }, { nombre: 'Amaderado', intensidad: 60 }, { nombre: 'Dulce', intensidad: 45 }, { nombre: 'Almizclado', intensidad: 30 }],
    notas: {
      salida: ['Ciruela', 'Melón blanco', 'Flor de cactus'],
      corazon: ['Azafrán', 'Canela'],
      fondo: ['Sándalo', 'Pachulí', 'Vainilla', 'Ámbar'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-44',
    nombre: '212 Tradicional Hombre',
    marcaId: 'carolina-herrera',
    marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 35500,
    stockProveedor: true,
    destacado: false,
    acordes: [{ nombre: 'Cítrico', intensidad: 100 }, { nombre: 'Verde', intensidad: 80 }, { nombre: 'Aromático', intensidad: 65 }, { nombre: 'Especiado', intensidad: 50 }, { nombre: 'Amaderado', intensidad: 35 }],
    notas: {
      salida: ['Notas verdes', 'Toronja', 'Bergamota', 'Lavanda'],
      corazon: ['Jengibre', 'Violeta', 'Gardenia', 'Salvia'],
      fondo: ['Almizcle', 'Sándalo', 'Incienso', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  // ─── CATÁLOGO EXTENDIDO — SEGUNDA OLEADA (159 productos) ─────
  { id: 'p-45', nombre: "Sauvage", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348901471534-247x247.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-46', nombre: "Sauvage", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348901368247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-47', nombre: "Sauvage", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348901486385-247x247.jpg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-48', nombre: "Jadore", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348900417878.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-49', nombre: "Jadore", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348901296632.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-50', nombre: "Miss Dior", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_4859-1.jpeg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-51', nombre: "Miss Dior Blooming Bouquet", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/51Ikxj6QTIL.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-52', nombre: "Fahrenheit", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348900012219.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-53', nombre: "Homme", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348901419147.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-54', nombre: "Homme Intense", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348900838185.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-55', nombre: "Poison", marcaId: 'dior', marca: { id: 'dior', nombre: "Dior" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3348900011687.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-56', nombre: "Bleu", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891074604.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-57', nombre: "Bleu", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_6456-1.jpeg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-58', nombre: "Coco Mademoiselle", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891165203.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-59', nombre: "Chance", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891265200.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-60', nombre: "Chance", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891264609-247x247.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-61', nombre: "No 5", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891255300.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-62', nombre: "Gabrielle", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891205251.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-63', nombre: "Allure Homme Sport", marcaId: 'chanel', marca: { id: 'chanel', nombre: "Chanel" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3145891236309.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-64', nombre: "Bloom", marcaId: 'gucci', marca: { id: 'gucci', nombre: "Gucci" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8005610481005.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-65', nombre: "Guilty Mujer", marcaId: 'gucci', marca: { id: 'gucci', nombre: "Gucci" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614227758162.jpg", precioVentaCrc: 45500, stockProveedor: true, destacado: false },
  { id: 'p-66', nombre: "Guilty Mujer", marcaId: 'gucci', marca: { id: 'gucci', nombre: "Gucci" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 90, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3616301976141.jpg", precioVentaCrc: 34500, stockProveedor: true, destacado: false },
  { id: 'p-67', nombre: "Bamboo", marcaId: 'gucci', marca: { id: 'gucci', nombre: "Gucci" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 75, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/737052925127.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-68', nombre: "Rush", marcaId: 'gucci', marca: { id: 'gucci', nombre: "Gucci" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 75, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8005610328799-1-247x247.jpg", precioVentaCrc: 28500, stockProveedor: true, destacado: false },
  { id: 'p-69', nombre: "Eros Hombre", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_2478.jpeg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-70', nombre: "Eros Hombre", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8011003813858.png", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-71', nombre: "Eros Mujer", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8011003823536.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-72', nombre: "Dylan Blue Mujer", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8011003839117.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-73', nombre: "Dylan Blue MEN", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8011003826490.jpg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-74', nombre: "Pour Homme", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8011003801619.jpg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-75', nombre: "Yellow", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_0984.jpeg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-76', nombre: "Crystal Noir", marcaId: 'versace', marca: { id: 'versace', nombre: "Versace" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 90, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/s-l400-2-2.jpg", precioVentaCrc: 34500, stockProveedor: true, destacado: false },
  { id: 'p-77', nombre: "Khamrah Dukhan Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_3725.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-78', nombre: "Nebras Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/71GCIiDMbfL._SL1287_-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-79', nombre: "Victoria Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-26-164743.png", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-80', nombre: "Habik Hombre", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2025-12-15-101913.png", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-81', nombre: "Brioche Vanille Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_3377-247x247.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-82', nombre: "Petra Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_6029-247x247.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-83', nombre: "Niche Emarati Classic Stone Unisex", marcaId: 'lattafa', marca: { id: 'lattafa', nombre: "Lattafa" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/lattafa-unisex-niche-emarati-classic-stone-edp-spray-34-oz-fragrances-6290360593043.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-84', nombre: "Tuscan Leather Unisex", marcaId: 'tom-ford', marca: { id: 'tom-ford', nombre: "Tom Ford" }, clasificacion: 'Nicho', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_4425.jpeg", precioVentaCrc: 78000, stockProveedor: true, destacado: false },
  { id: 'p-85', nombre: "Costa Azzurra", marcaId: 'tom-ford', marca: { id: 'tom-ford', nombre: "Tom Ford" }, clasificacion: 'Nicho', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9983.jpeg", precioVentaCrc: 78000, stockProveedor: true, destacado: false },
  { id: 'p-86', nombre: "HER", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_6669.jpeg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-87', nombre: "HER Intense", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_5718.jpeg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-88', nombre: "Hero Hombre", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_0942.jpeg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-89', nombre: "Hero Hombre", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-02-10-114624.png", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-90', nombre: "Brit Hombre", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/5045252668009.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-91', nombre: "Brit Mujer", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9796-247x247.jpeg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-92', nombre: "London Hombre", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614226905215.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-93', nombre: "London Mujer", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614226905185.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-94', nombre: "Weekend Mujer", marcaId: 'burberry', marca: { id: 'burberry', nombre: "Burberry" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614226905284.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-95', nombre: "Pour Homme", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-104456-247x247.png", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-96', nombre: "Man In Black", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_5052.jpeg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-97', nombre: "Man Wood Essence", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/4199-318d3add-1200.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-98', nombre: "Omnia Cristalline", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/783320420566.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-99', nombre: "Omnia Coral", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_1554-247x247.jpeg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-100', nombre: "BLV", marcaId: 'bvlgari', marca: { id: 'bvlgari', nombre: "Bvlgari" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/783320402739-247x247.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-101', nombre: "Invictus Tradicional", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_2197.jpeg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-102', nombre: "Invictus Aqua", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_6049-247x247.jpeg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-103', nombre: "1 Million Royal Parfum", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/paco-rabanne-mens-1-million-royal-edp-spray-34-oz-fragrances-3349668617050.jpg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-104', nombre: "Lady Million Royal", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3349668617173.png", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-105', nombre: "Olympea", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'Parfum', volumenMl: 80, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-03-09-143135-247x247.png", precioVentaCrc: 46500, stockProveedor: true, destacado: false },
  { id: 'p-106', nombre: "Fame Mujer", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3349668594412-247x247.jpg", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-107', nombre: "XS Black Hombre", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3349668550654.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-108', nombre: "XS Black Mujer", marcaId: 'paco-rabanne', marca: { id: 'paco-rabanne', nombre: "Paco Rabanne" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Black-XS-For-Her-de-Paco-Rabanne-247x247.jpg", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-109', nombre: "Hawas Mujer", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/614514331019.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-110', nombre: "Hawas Venom Hombre", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-115113-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-111', nombre: "Hawas Nautilus Hombre", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-114110-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-112', nombre: "Daarej Mujer", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/614514177013-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-113', nombre: "Daarej Hombre", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_8276-247x247.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-114', nombre: "La Yuqawam Tradicional Mujer", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 75, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/614514204054-247x247.jpg", precioVentaCrc: 13000, stockProveedor: true, destacado: false },
  { id: 'p-115', nombre: "La Yuqawam Tobacco Blaze Hombre", marcaId: 'rasasi', marca: { id: 'rasasi', nombre: "Rasasi" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 75, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/614514204061.jpg", precioVentaCrc: 13000, stockProveedor: true, destacado: false },
  { id: 'p-116', nombre: "Amber OUD Black Unisex", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 150, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_4551-247x247.jpeg", precioVentaCrc: 25500, stockProveedor: true, destacado: false },
  { id: 'p-117', nombre: "Royal Musk Unisex", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_6795-1.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-118', nombre: "Musk Collection Unisex", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_1269.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-119', nombre: "L'aventure Intense Hombre", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/al-haramain-l_aaventure-intense-spray-100-ml.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-120', nombre: "L'aventure Blanche Hombre", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/ahp1909-laventure-blanche-box-bottle_500pixels-x-500-pixels_3.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-121', nombre: "Amber Musk Unisex", marcaId: 'al-haramain', marca: { id: 'al-haramain', nombre: "Al Haramain" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/6291100130634.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-122', nombre: "Club De Nuit Bling Unisex", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Unisex', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/fit.140942.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-123', nombre: "Connoisseur Mujer", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_7033.jpeg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-124', nombre: "Connoisseur Hombre", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_7029.png", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-125', nombre: "Legesi Hombre", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/MmM0NjA5Mj_1-1000x1000-1-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-126', nombre: "Legesi Mujer", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/15527_f.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-127', nombre: "The Pride Hombre", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-07-28-180200-247x247.png", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-128', nombre: "The Pride Mujer", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-07-28-175822-247x247.png", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-129', nombre: "Match Point Hombre", marcaId: 'armaf', marca: { id: 'armaf', nombre: "Armaf" }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/s-l1200-4-1-247x247.jpg", precioVentaCrc: 17000, stockProveedor: true, destacado: false },
  { id: 'p-130', nombre: "Paradigme Hombre", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-05-18-145753-247x247.png", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-131', nombre: "Carbon", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-27-165427-247x247.png", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-132', nombre: "Candy", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Gourmand', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435137727087.jpg", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-133', nombre: "Luna Rosa", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435137729180.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-134', nombre: "La Femme L'eau", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435137765065.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-135', nombre: "Black", marcaId: 'prada', marca: { id: 'prada', nombre: "Prada" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435137782949.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-136', nombre: "Good Girl", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 150, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061958483.jpg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-137', nombre: "BAD BOY", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061923245.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-138', nombre: "Herrera Tradicional Mujer", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061934234-247x247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-139', nombre: "Herrera Tradicional Hombre", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061081600.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-140', nombre: "CH HC Hombre", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061786161.jpg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-141', nombre: "Chic Hombre", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061954966.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-142', nombre: "Chic Mujer", marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: "Carolina Herrera" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8411061071601.jpg", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-143', nombre: "Donna Mujer", marcaId: 'valentino', marca: { id: 'valentino', nombre: "Valentino" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9988-247x247.jpeg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-144', nombre: "Uomo Hombre", marcaId: 'valentino', marca: { id: 'valentino', nombre: "Valentino" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614272732209.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-145', nombre: "Valentina Mujer", marcaId: 'valentino', marca: { id: 'valentino', nombre: "Valentino" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 80, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614272731929.jpg", precioVentaCrc: 40500, stockProveedor: true, destacado: false },
  { id: 'p-146', nombre: "Born In Roma Donna Purple Melancholia", marcaId: 'valentino', marca: { id: 'valentino', nombre: "Valentino" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-06-29-184424-247x247.png", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-147', nombre: "Acqua Di GIO Profondo", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-03-20-164415-247x247.png", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-148', nombre: "Acqua Di GIO Intense", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/giorgio-armani-mens-acqua-gio-intense-edp-spray-34-oz-fragrances-3614274644449-1.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-149', nombre: "Acqua Di GIO Absolu", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 125, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614271992932.jpg", precioVentaCrc: 63000, stockProveedor: true, destacado: false },
  { id: 'p-150', nombre: "Code Mujer", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 75, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3360375010972.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-151', nombre: "Si Passione", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614271994844.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-152', nombre: "Emporio Stronger Whit YOU Hombre", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3605522040588.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-153', nombre: "Emporio LUI Hombre", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3360372061830.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-154', nombre: "Emporio LEI Mujer", marcaId: 'armani', marca: { id: 'armani', nombre: "Giorgio Armani" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/emporio-247x247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-155', nombre: "The ONE Hombre", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423473021360.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-156', nombre: "The ONE Hombre", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 150, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423473021216.jpg", precioVentaCrc: 57000, stockProveedor: true, destacado: false },
  { id: 'p-157', nombre: "The Only ONE Mujer", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423478452657-1-247x247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-158', nombre: "K", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423473049456.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-159', nombre: "Pour Homme", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 125, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423473020776.jpg", precioVentaCrc: 47500, stockProveedor: true, destacado: false },
  { id: 'p-160', nombre: "Pour Femme EDT", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3423473020622.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-161', nombre: "Devotion Hombre", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: "Dolce & Gabbana" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-24-085458-247x247.png", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-162', nombre: "Bottled", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614229828535.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-163', nombre: "Bottled", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/hugo-boss-mens-bottled-parfum-6-76-oz-fragrances-3616303173104-y-a2t9k_1.jpg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-164', nombre: "Man", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/737052515045.jpg", precioVentaCrc: 76000, stockProveedor: true, destacado: false },
  { id: 'p-165', nombre: "Woman", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/737052057989.jpg", precioVentaCrc: 45500, stockProveedor: true, destacado: false },
  { id: 'p-166', nombre: "Orange Hombre", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/D_NQ_NP_888039-MCR49064376607_022022-W-247x247.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-167', nombre: "Orange Mujer", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 75, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/737052238128.jpg", precioVentaCrc: 28500, stockProveedor: true, destacado: false },
  { id: 'p-168', nombre: "Dark Blue", marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: "Hugo Boss" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 75, familiaOlfativa: 'Acuático', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/737052031415.jpg", precioVentaCrc: 28500, stockProveedor: true, destacado: false },
  { id: 'p-169', nombre: "L'homme", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3365440316560.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-170', nombre: "Y", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614271716026-1.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-171', nombre: "Y", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614273318105.jpg", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-172', nombre: "Libre Mujer", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/LIBRE-YSL_800x.jpg", precioVentaCrc: 45500, stockProveedor: true, destacado: false },
  { id: 'p-173', nombre: "Libre Mujer", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 90, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614273321891.jpg", precioVentaCrc: 34500, stockProveedor: true, destacado: false },
  { id: 'p-174', nombre: "Opium", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3365440556263.jpg", precioVentaCrc: 45500, stockProveedor: true, destacado: false },
  { id: 'p-175', nombre: "Kouros", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3365440003866.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-176', nombre: "La Nuit De L'homme Le Parfum", marcaId: 'ysl', marca: { id: 'ysl', nombre: "Yves Saint Laurent" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/300670.webp", precioVentaCrc: 58000, stockProveedor: true, destacado: false },
  { id: 'p-177', nombre: "Eternity Hombre", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3614229135145.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-178', nombre: "Eternity Mujer", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/03.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-179', nombre: "Obsession Mujer", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300103409.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-180', nombre: "Obsession Hombre", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 125, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300106516.jpg", precioVentaCrc: 47500, stockProveedor: true, destacado: false },
  { id: 'p-181', nombre: "Euphoria Tradicional Mujer", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300162505.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-182', nombre: "Euphoria Tradicional Hombre", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300178278.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-183', nombre: "CK BE", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Unisex', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300104406.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-184', nombre: "Contradiction Mujer", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300602513.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-185', nombre: "Contradiction Hombre", marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: "Calvin Klein" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/88300000319.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-186', nombre: "Gentleman Originale", marcaId: 'givenchy', marca: { id: 'givenchy', nombre: "Givenchy" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/givenchy-mens-gentleman-edt-spray-34-oz-fragrances-3274872487376.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-187', nombre: "Pour Homme", marcaId: 'givenchy', marca: { id: 'givenchy', nombre: "Givenchy" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3274870303166.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-188', nombre: "Very Irresistible EDT", marcaId: 'givenchy', marca: { id: 'givenchy', nombre: "Givenchy" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 75, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3274872369412.jpg", precioVentaCrc: 28500, stockProveedor: true, destacado: false },
  { id: 'p-189', nombre: "Organza", marcaId: 'givenchy', marca: { id: 'givenchy', nombre: "Givenchy" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3274872389977-247x247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-190', nombre: "Amarige", marcaId: 'givenchy', marca: { id: 'givenchy', nombre: "Givenchy" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3274878122561.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-191', nombre: "Legend", marcaId: 'montblanc', marca: { id: 'montblanc', nombre: "Montblanc" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3386460032681.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-192', nombre: "Legend RED", marcaId: 'montblanc', marca: { id: 'montblanc', nombre: "Montblanc" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3386460127950.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-193', nombre: "Explorer", marcaId: 'montblanc', marca: { id: 'montblanc', nombre: "Montblanc" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3386460101035-247x247.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-194', nombre: "Individuel Hombre", marcaId: 'montblanc', marca: { id: 'montblanc', nombre: "Montblanc" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 75, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3386460028394.jpg", precioVentaCrc: 28500, stockProveedor: true, destacado: false },
  { id: 'p-195', nombre: "Signature Mujer", marcaId: 'montblanc', marca: { id: 'montblanc', nombre: "Montblanc" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Floral', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3386460113588.jpg", precioVentaCrc: 45500, stockProveedor: true, destacado: false },
  { id: 'p-196', nombre: "Chrome", marcaId: 'azzaro', marca: { id: 'azzaro', nombre: "Azzaro" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3351500920037.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-197', nombre: "Pour Homme", marcaId: 'azzaro', marca: { id: 'azzaro', nombre: "Azzaro" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/3351500980406.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-198', nombre: "Wanted Hombre", marcaId: 'azzaro', marca: { id: 'azzaro', nombre: "Azzaro" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_2425-247x247.jpeg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-199', nombre: "Le Male Elixir Hombre", marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: "Jean Paul" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 125, familiaOlfativa: 'Oriental', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9129-1.jpeg", precioVentaCrc: 72500, stockProveedor: true, destacado: false },
  { id: 'p-200', nombre: "Scandal Hombre", marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: "Jean Paul" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435415030885-247x247.jpg", precioVentaCrc: 38000, stockProveedor: true, destacado: false },
  { id: 'p-201', nombre: "Scandal Le Parfum Mujer", marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: "Jean Paul" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'Parfum', volumenMl: 80, familiaOlfativa: 'Gourmand', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435415050760.jpg", precioVentaCrc: 46500, stockProveedor: true, destacado: false },
  { id: 'p-202', nombre: "La Belle", marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: "Jean Paul" }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/8435415017244.jpg", precioVentaCrc: 50500, stockProveedor: true, destacado: false },
  { id: 'p-203', nombre: "Le Beau Hombre", marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: "Jean Paul" }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 125, familiaOlfativa: 'Fresco', imagenUrl: "https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9119.png", precioVentaCrc: 47500, stockProveedor: true, destacado: false },
];

export const PERFUMES_SIMULADOS = CATALOGO_PERFUMES;

export function obtenerPerfumePorId(id: string): Perfume | undefined {
  return CATALOGO_PERFUMES.find((p) => p.id === id);
}
