import type { Perfume } from './Perfume.tipos';

export const CATALOGO_PERFUMES: Perfume[] = [
  // ─── MUJER ──────────────────────────────────────────────
  { id: 'p-01', nombre: 'Ambassador Pink', marcaId: 'gisada', marca: { id: 'gisada', nombre: 'Gisada' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 37500, stockProveedor: true },
  { id: 'p-02', nombre: 'My Way (Recharge)', marcaId: 'armani', marca: { id: 'armani', nombre: 'Giorgio Armani' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 61000, stockProveedor: true },
  { id: 'p-03', nombre: 'My Way Floral', marcaId: 'armani', marca: { id: 'armani', nombre: 'Giorgio Armani' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 50500, stockProveedor: true },
  { id: 'p-04', nombre: 'Daisy Wild Eau So Extra', marcaId: 'marc-jacobs', marca: { id: 'marc-jacobs', nombre: 'Marc Jacobs' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 50500, stockProveedor: true },
  { id: 'p-05', nombre: 'Paradoxe Virtual Flower', marcaId: 'prada', marca: { id: 'prada', nombre: 'Prada' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 58000, stockProveedor: true },
  { id: 'p-06', nombre: 'Seductive', marcaId: 'guess', marca: { id: 'guess', nombre: 'Guess' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 13500, stockProveedor: true },
  { id: 'p-07', nombre: '9 PM Mujer', marcaId: 'afnan', marca: { id: 'afnan', nombre: 'Afnan' }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: null, precioVentaCrc: 19500, stockProveedor: true },
  { id: 'p-08', nombre: 'Hawas Reina', marcaId: 'rasasi', marca: { id: 'rasasi', nombre: 'Rasasi' }, clasificacion: 'Arabe', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 22500, stockProveedor: true },
  { id: 'p-09', nombre: 'La Vida Es Bella (Estuche 2 piezas)', marcaId: 'lancome', marca: { id: 'lancome', nombre: 'Lancôme' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', descripcion: 'Set de regalo, 2 piezas.', imagenUrl: null, precioVentaCrc: 76000, stockProveedor: true },
  { id: 'p-10', nombre: 'La Vida Es Bella', marcaId: 'lancome', marca: { id: 'lancome', nombre: 'Lancôme' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 62500, stockProveedor: true },
  { id: 'p-11', nombre: 'Divine Mujer (Edición Colección)', marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: 'Jean Paul' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 55500, stockProveedor: true },
  { id: 'p-12', nombre: 'Divine Mujer (Estuche 3 piezas)', marcaId: 'jean-paul', marca: { id: 'jean-paul', nombre: 'Jean Paul' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', descripcion: 'Set de regalo, 3 piezas.', imagenUrl: null, precioVentaCrc: 71000, stockProveedor: true },
  { id: 'p-13', nombre: 'Libre Berry Crush', marcaId: 'ysl', marca: { id: 'ysl', nombre: 'Yves Saint Laurent' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Oriental', imagenUrl: null, precioVentaCrc: 74500, stockProveedor: true },
  { id: 'p-14', nombre: 'My Way', marcaId: 'armani', marca: { id: 'armani', nombre: 'Giorgio Armani' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 59000, stockProveedor: true },
  { id: 'p-15', nombre: 'My Way Nectar', marcaId: 'armani', marca: { id: 'armani', nombre: 'Giorgio Armani' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 90, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 62500, stockProveedor: true },
  { id: 'p-16', nombre: "L'Imperatrice", marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Citrico', imagenUrl: null, precioVentaCrc: 19500, stockProveedor: true },
  { id: 'p-17', nombre: 'Halloween Tradicional', marcaId: 'jesus-del-pozo', marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: null, precioVentaCrc: 17000, stockProveedor: true },
  { id: 'p-18', nombre: 'Acqua Di Parisis', marcaId: 'reyane', marca: { id: 'reyane', nombre: 'Reyane Tradition' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: null, precioVentaCrc: 11500, stockProveedor: true },
  { id: 'p-19', nombre: 'Halloween Blue Drop', marcaId: 'jesus-del-pozo', marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: null, precioVentaCrc: 19500, stockProveedor: true },
  { id: 'p-20', nombre: 'Curve Chill Mujer', marcaId: 'liz-claiborne', marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: null, precioVentaCrc: 10000, stockProveedor: true },
  { id: 'p-21', nombre: 'Tommy Girl', marcaId: 'tommy-hilfiger', marca: { id: 'tommy-hilfiger', nombre: 'Tommy Hilfiger' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: null, precioVentaCrc: 14500, stockProveedor: true },
  { id: 'p-22', nombre: 'Thank U, Next', marcaId: 'ariana-grande', marca: { id: 'ariana-grande', nombre: 'Ariana Grande' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 23500, stockProveedor: true },
  { id: 'p-23', nombre: 'Happy Mujer', marcaId: 'clinique', marca: { id: 'clinique', nombre: 'Clinique' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Citrico', imagenUrl: null, precioVentaCrc: 21000, stockProveedor: true },
  { id: 'p-24', nombre: 'Fantasy Tradicional', marcaId: 'britney-spears', marca: { id: 'britney-spears', nombre: 'Britney Spears' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 13000, stockProveedor: true },
  { id: 'p-25', nombre: 'Curve Crush Mujer', marcaId: 'liz-claiborne', marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Floral', imagenUrl: null, precioVentaCrc: 13000, stockProveedor: true },
  { id: 'p-26', nombre: 'Ari', marcaId: 'ariana-grande', marca: { id: 'ariana-grande', nombre: 'Ariana Grande' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 21000, stockProveedor: true },
  { id: 'p-34', nombre: '212 Tradicional Mujer', marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' }, clasificacion: 'Diseñador', genero: 'Femenino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Fresco', imagenUrl: null, precioVentaCrc: 41500, stockProveedor: true },

  // ─── HOMBRE ─────────────────────────────────────────────
  { id: 'p-27', nombre: 'In Motion (Tester)', marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: 'Hugo Boss' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.', imagenUrl: null, precioVentaCrc: 14500, stockProveedor: true },
  { id: 'p-28', nombre: 'Voyage', marcaId: 'nautica', marca: { id: 'nautica', nombre: 'Nautica' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: null, precioVentaCrc: 8500, stockProveedor: true },
  { id: 'p-29', nombre: 'CK One', marcaId: 'calvin-klein', marca: { id: 'calvin-klein', nombre: 'Calvin Klein' }, clasificacion: 'Diseñador', genero: 'Unisex', concentracion: 'EDT', volumenMl: 200, familiaOlfativa: 'Citrico', imagenUrl: null, precioVentaCrc: 17500, stockProveedor: true },
  { id: 'p-30', nombre: 'Bottled Beyond', marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: 'Hugo Boss' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 150, familiaOlfativa: 'Amaderado', imagenUrl: null, precioVentaCrc: 54000, stockProveedor: true },
  { id: 'p-31', nombre: "L'Homme", marcaId: 'ysl', marca: { id: 'ysl', nombre: 'Yves Saint Laurent' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: null, precioVentaCrc: 61500, stockProveedor: true },
  { id: 'p-32', nombre: 'The Most Wanted (Tester)', marcaId: 'azzaro', marca: { id: 'azzaro', nombre: 'Azzaro' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Parfum', volumenMl: 100, familiaOlfativa: 'Oriental', descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.', imagenUrl: null, precioVentaCrc: 40000, stockProveedor: true },
  { id: 'p-33', nombre: 'Uomo Born In Roma Purple Melancholia', marcaId: 'valentino', marca: { id: 'valentino', nombre: 'Valentino' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: null, precioVentaCrc: 64000, stockProveedor: true },
  { id: 'p-35', nombre: 'Light Blue Hombre', marcaId: 'dolce-gabbana', marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 125, familiaOlfativa: 'Citrico', imagenUrl: null, precioVentaCrc: 33000, stockProveedor: true },
  { id: 'p-36', nombre: 'In Motion', marcaId: 'hugo-boss', marca: { id: 'hugo-boss', nombre: 'Hugo Boss' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: null, precioVentaCrc: 16500, stockProveedor: true },
  { id: 'p-37', nombre: 'Club De Nuit Intense', marcaId: 'armaf', marca: { id: 'armaf', nombre: 'Armaf' }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDT', volumenMl: 105, familiaOlfativa: 'Amaderado', imagenUrl: null, precioVentaCrc: 17000, stockProveedor: true },
  { id: 'p-38', nombre: '9 PM Hombre', marcaId: 'afnan', marca: { id: 'afnan', nombre: 'Afnan' }, clasificacion: 'Arabe', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Oriental', imagenUrl: null, precioVentaCrc: 14500, stockProveedor: true },
  { id: 'p-39', nombre: '360 Red', marcaId: 'perry-ellis', marca: { id: 'perry-ellis', nombre: 'Perry Ellis' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Amaderado', imagenUrl: null, precioVentaCrc: 14500, stockProveedor: true },
  { id: 'p-40', nombre: 'Blue', marcaId: 'nautica', marca: { id: 'nautica', nombre: 'Nautica' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Acuático', imagenUrl: null, precioVentaCrc: 8500, stockProveedor: true },
  { id: 'p-41', nombre: 'Curve Chill Hombre', marcaId: 'liz-claiborne', marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Colonia', volumenMl: 125, familiaOlfativa: 'Fresco', imagenUrl: null, precioVentaCrc: 10000, stockProveedor: true },
  { id: 'p-42', nombre: 'Toy Boy', marcaId: 'moschino', marca: { id: 'moschino', nombre: 'Moschino' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDP', volumenMl: 100, familiaOlfativa: 'Gourmand', imagenUrl: null, precioVentaCrc: 28000, stockProveedor: true },
  { id: 'p-43', nombre: 'Curve Connect Hombre', marcaId: 'liz-claiborne', marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'Colonia', volumenMl: 125, familiaOlfativa: 'Fresco', imagenUrl: null, precioVentaCrc: 10000, stockProveedor: true },
  { id: 'p-44', nombre: '212 Tradicional Hombre', marcaId: 'carolina-herrera', marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' }, clasificacion: 'Diseñador', genero: 'Masculino', concentracion: 'EDT', volumenMl: 100, familiaOlfativa: 'Citrico', imagenUrl: null, precioVentaCrc: 35500, stockProveedor: true },
];

export const PERFUMES_SIMULADOS = CATALOGO_PERFUMES;

export function obtenerPerfumePorId(id: string): Perfume | undefined {
  return CATALOGO_PERFUMES.find((p) => p.id === id);
}
