import type { Perfume } from './Perfume.tipos';

export const CATALOGO_PERFUMES: Perfume[] = [
  // ─── MUJER ──────────────────────────────────────────────
  {
    id: 'p-01',
    nombre: 'Ambassador Pink',
    marcaId: 'gisada',
    marca: { id: 'gisada', nombre: 'Gisada' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-120327.png',
    precioVentaCrc: 37500,
    stockProveedor: true,
    notas: {
      salida: ['Albaricoque', 'Pera', 'Bergamota', 'Hojas de violeta'],
      corazon: ['Ciruela', 'Nardos', 'Frambuesa', 'Rosa'],
      fondo: ['Vainilla', 'Haba tonka', 'Pachulí', 'Sándalo'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-02',
    nombre: 'My Way (Recharge)',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'Parfum',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/img_9972-247x247.png',
    precioVentaCrc: 61000,
    stockProveedor: true,
    notas: {
      salida: ['Flor de azahar del naranjo', 'Naranja amarga', 'Bergamota'],
      corazon: ['Iris Pallida', 'Nardo de la India', 'Ambreta'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-03',
    nombre: 'My Way Floral',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-143707-247x247.jpg',
    precioVentaCrc: 50500,
    stockProveedor: true,
    notas: {
      salida: ['Flor de azahar del naranjo', 'Mandarina verde', 'Naranja amarga'],
      corazon: ['Nardo de la India', 'Neroli'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-04',
    nombre: 'Daisy Wild Eau So Extra',
    marcaId: 'marc-jacobs',
    marca: { id: 'marc-jacobs', nombre: 'Marc Jacobs' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-165837.png',
    precioVentaCrc: 50500,
    stockProveedor: true,
    notas: {
      salida: ['Flor de plátano', 'Pera', 'Bergamota'],
      corazon: ['Margarita de chocolate', 'Jazmín'],
      fondo: ['Vainilla', 'Ámbar', 'Sándalo'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-05',
    nombre: 'Paradoxe Virtual Flower',
    marcaId: 'prada',
    marca: { id: 'prada', nombre: 'Prada' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-122328.png',
    precioVentaCrc: 58000,
    stockProveedor: true,
    notas: {
      salida: ['Bergamota italiana', 'Cítricos'],
      corazon: ['Jazmín', 'Neroli'],
      fondo: ['Almizcle', 'Semillas de ambreta'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-06',
    nombre: 'Seductive',
    marcaId: 'guess',
    marca: { id: 'guess', nombre: 'Guess' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-27-153727-247x247.png',
    precioVentaCrc: 13500,
    stockProveedor: true,
    notas: {
      salida: ['Pera', 'Bergamota', 'Grosellas negras'],
      corazon: ['Flor de azahar del naranjo', 'Jazmín', 'Raíz de lirio'],
      fondo: ['Vainilla', 'Madera de cachemira', 'Incienso de olíbano'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-07',
    nombre: '9 PM Mujer',
    marcaId: 'afnan',
    marca: { id: 'afnan', nombre: 'Afnan' },
    clasificacion: 'Arabe',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/629017072607-247x247.jpg',
    precioVentaCrc: 19500,
    stockProveedor: true,
    notas: {
      salida: ['Frambuesa', 'Manzana', 'Naranja', 'Violeta'],
      corazon: ['Rosa', 'Iris', 'Peonía', 'Jazmín'],
      fondo: ['Ámbar', 'Cedro', 'Ciprés', 'Pino'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-08',
    nombre: 'Hawas Reina',
    marcaId: 'rasasi',
    marca: { id: 'rasasi', nombre: 'Rasasi' },
    clasificacion: 'Arabe',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-161632.jpg',
    precioVentaCrc: 22500,
    stockProveedor: true,
    notas: {
      salida: ['Granada', 'Manzana', 'Toronja'],
      corazon: ['Jazmín sambac', 'Iris', 'Cítricos'],
      fondo: ['Praliné', 'Pachulí', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-09',
    nombre: 'La Vida Es Bella (Estuche 2 piezas)',
    marcaId: 'lancome',
    marca: { id: 'lancome', nombre: 'Lancôme' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    descripcion: 'Set de regalo, 2 piezas.',
    imagenUrl: null,
    precioVentaCrc: 76000,
    stockProveedor: true,
    notas: {
      salida: ['Grosellas negras', 'Pera'],
      corazon: ['Iris', 'Jazmín', 'Flor de azahar del naranjo'],
      fondo: ['Praliné', 'Vainilla', 'Pachulí', 'Haba tonka'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-10',
    nombre: 'La Vida Es Bella',
    marcaId: 'lancome',
    marca: { id: 'lancome', nombre: 'Lancôme' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 62500,
    stockProveedor: true,
    notas: {
      salida: ['Grosellas negras', 'Pera'],
      corazon: ['Iris', 'Jazmín', 'Flor de azahar del naranjo'],
      fondo: ['Praliné', 'Vainilla', 'Pachulí', 'Haba tonka'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-11',
    nombre: 'Divine Mujer (Edición Colección)',
    marcaId: 'jean-paul',
    marca: { id: 'jean-paul', nombre: 'Jean Paul' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: null,
    precioVentaCrc: 55500,
    stockProveedor: true,
    notas: {
      salida: ['Calipsone', 'Bayas rojas', 'Bergamota'],
      corazon: ['Azucena', 'Ylang-ylang', 'Jazmín'],
      fondo: ['Merengue', 'Almizcle', 'Pachulí'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-12',
    nombre: 'Divine Mujer (Estuche 3 piezas)',
    marcaId: 'jean-paul',
    marca: { id: 'jean-paul', nombre: 'Jean Paul' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    descripcion: 'Set de regalo, 3 piezas.',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/jean-paul-gaultier-ladies-divine-gift-set-fragrances-8435415103169.jpg',
    precioVentaCrc: 71000,
    stockProveedor: true,
    notas: {
      salida: ['Calipsone', 'Bayas rojas', 'Bergamota'],
      corazon: ['Azucena', 'Ylang-ylang', 'Jazmín'],
      fondo: ['Merengue', 'Almizcle', 'Pachulí'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-13',
    nombre: 'Libre Berry Crush',
    marcaId: 'ysl',
    marca: { id: 'ysl', nombre: 'Yves Saint Laurent' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-08-24-121023.png',
    precioVentaCrc: 74500,
    stockProveedor: true,
    notas: {
      salida: ['Frambuesa', 'Mandarina'],
      corazon: ['Flor de azahar del naranjo', 'Lavanda'],
      fondo: ['Vainilla Bourbon', 'Coco', 'Almizcle'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-14',
    nombre: 'My Way',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Floral',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3614272907690.jpg',
    precioVentaCrc: 59000,
    stockProveedor: true,
    notas: {
      salida: ['Flor de azahar del naranjo', 'Bergamota'],
      corazon: ['Nardo de la India', 'Jazmín de la India'],
      fondo: ['Vainilla de Madagascar', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-15',
    nombre: 'My Way Nectar',
    marcaId: 'armani',
    marca: { id: 'armani', nombre: 'Giorgio Armani' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 90,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 62500,
    stockProveedor: true,
    notas: {
      salida: ['Pera', 'Flor de azahar del naranjo', 'Bergamota'],
      corazon: ['Nardos', 'Jazmín', 'Hojas de violeta'],
      fondo: ['Vainilla Bourbon', 'Almizcle blanco', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-16',
    nombre: "L'Imperatrice",
    marcaId: 'dolce-gabbana',
    marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 19500,
    stockProveedor: true,
    notas: {
      salida: ['Kiwi', 'Ruibarbo', 'Pimienta rosa'],
      corazon: ['Sandía', 'Ciclamen', 'Jazmín'],
      fondo: ['Limonero', 'Almizcle', 'Sándalo'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-17',
    nombre: 'Halloween Tradicional',
    marcaId: 'jesus-del-pozo',
    marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/8431754342016.jpg',
    precioVentaCrc: 17000,
    stockProveedor: true,
    notas: {
      salida: ['Violeta', 'Notas marinas', 'Hoja de plátano', 'Petitgrain'],
      corazon: ['Violeta', 'Magnolia', 'Lirio de los valles', 'Pimienta'],
      fondo: ['Incienso', 'Vainilla de Madagascar', 'Sándalo', 'Mirra'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-18',
    nombre: 'Acqua Di Parisis',
    marcaId: 'reyane',
    marca: { id: 'reyane', nombre: 'Reyane Tradition' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 11500,
    stockProveedor: true,
  },
  {
    id: 'p-19',
    nombre: 'Halloween Blue Drop',
    marcaId: 'jesus-del-pozo',
    marca: { id: 'jesus-del-pozo', nombre: 'Jesus Del Pozo' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 19500,
    stockProveedor: true,
    notas: {
      salida: ['Cítricos', 'Manzana verde', 'Lavanda'],
      corazon: ['Flores blancas', 'Jazmín', 'Violeta'],
      fondo: ['Almizcle', 'Cedro', 'Ámbar', 'Especias'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-20',
    nombre: 'Curve Chill Mujer',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    notas: {
      salida: ['Té verde', 'Jengibre', 'Limón'],
      corazon: ['Peonía', 'Fresia', 'Guisante de olor'],
      fondo: ['Almizcle', 'Cedro', 'Vetiver'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-21',
    nombre: 'Tommy Girl',
    marcaId: 'tommy-hilfiger',
    marca: { id: 'tommy-hilfiger', nombre: 'Tommy Hilfiger' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 14500,
    stockProveedor: true,
    notas: {
      salida: ['Manzano en flor', 'Camelia', 'Mandarina', 'Grosellas negras'],
      corazon: ['Limón', 'Madreselva', 'Rosa', 'Lirio'],
      fondo: ['Magnolia', 'Cedro', 'Sándalo', 'Jazmín'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-22',
    nombre: 'Thank U, Next',
    marcaId: 'ariana-grande',
    marca: { id: 'ariana-grande', nombre: 'Ariana Grande' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 23500,
    stockProveedor: true,
    notas: {
      salida: ['Pera blanca', 'Frambuesa'],
      corazon: ['Crema de coco', 'Rosa rosada'],
      fondo: ['Macarrones dulces', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-23',
    nombre: 'Happy Mujer',
    marcaId: 'clinique',
    marca: { id: 'clinique', nombre: 'Clinique' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 21000,
    stockProveedor: true,
    notas: {
      salida: ['Naranja', 'Toronja sanguina', 'Mandarina', 'Bergamota'],
      corazon: ['Lirio de los valles', 'Fresia', 'Orquídea', 'Rosa'],
      fondo: ['Mimosa', 'Azucena', 'Magnolia', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-24',
    nombre: 'Fantasy Tradicional',
    marcaId: 'britney-spears',
    marca: { id: 'britney-spears', nombre: 'Britney Spears' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/719346065405.jpg',
    precioVentaCrc: 13000,
    stockProveedor: true,
    notas: {
      salida: ['Kiwi', 'Lichi rojo', 'Membrillo'],
      corazon: ['Chocolate blanco', 'Quequito', 'Orquídea', 'Jazmín'],
      fondo: ['Almizcle', 'Raíz de lirio', 'Notas amaderadas'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-25',
    nombre: 'Curve Crush Mujer',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Floral',
    imagenUrl: null,
    precioVentaCrc: 13000,
    stockProveedor: true,
    notas: {
      salida: ['Cítricos', 'Té floral', 'Jengibre'],
      corazon: ['Leche', 'Canela', 'Cardamomo', 'Orquídea'],
      fondo: ['Vainilla', 'Azúcar', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-26',
    nombre: 'Ari',
    marcaId: 'ariana-grande',
    marca: { id: 'ariana-grande', nombre: 'Ariana Grande' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/812256020301-247x247.jpg',
    precioVentaCrc: 21000,
    stockProveedor: true,
    notas: {
      salida: ['Frambuesa', 'Pera', 'Toronja'],
      corazon: ['Orquídea de vainilla', 'Lirio de los valles', 'Rosa'],
      fondo: ['Malvavisco', 'Almizcle', 'Notas amaderadas'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-34',
    nombre: '212 Tradicional Mujer',
    marcaId: 'carolina-herrera',
    marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' },
    clasificacion: 'Diseñador',
    genero: 'Femenino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 41500,
    stockProveedor: true,
    notas: {
      salida: ['Flor de azahar del naranjo', 'Flor de cactus', 'Mandarina', 'Bergamota'],
      corazon: ['Azucena', 'Gardenia', 'Fresia', 'Jazmín'],
      fondo: ['Almizcle', 'Sándalo'],
    },
    duracion: 4,
    proyeccion: 3,
  },

  // ─── HOMBRE ─────────────────────────────────────────────
  {
    id: 'p-27',
    nombre: 'In Motion (Tester)',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3616301623328.jpg',
    precioVentaCrc: 14500,
    stockProveedor: true,
    notas: {
      salida: ['Naranja', 'Albahaca', 'Hojas de violeta', 'Bergamota'],
      corazon: ['Nuez moscada', 'Canela', 'Pimienta rosa', 'Cardamomo'],
      fondo: ['Sándalo', 'Vetiver', 'Notas amaderadas', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-28',
    nombre: 'Voyage',
    marcaId: 'nautica',
    marca: { id: 'nautica', nombre: 'Nautica' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: null,
    precioVentaCrc: 8500,
    stockProveedor: true,
    notas: {
      salida: ['Manzana verde', 'Hojas verdes'],
      corazon: ['Flor de loto', 'Mimosa'],
      fondo: ['Almizcle', 'Cedro', 'Musgo de roble', 'Ámbar'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-29',
    nombre: 'CK One',
    marcaId: 'calvin-klein',
    marca: { id: 'calvin-klein', nombre: 'Calvin Klein' },
    clasificacion: 'Diseñador',
    genero: 'Unisex',
    concentracion: 'EDT',
    volumenMl: 200,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 17500,
    stockProveedor: true,
    notas: {
      salida: ['Limón', 'Bergamota', 'Mandarina', 'Piña', 'Cardamomo'],
      corazon: ['Lirio de los valles', 'Jazmín', 'Violeta', 'Nuez moscada'],
      fondo: ['Almizcle', 'Cedro', 'Sándalo', 'Musgo de roble', 'Ámbar'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-30',
    nombre: 'Bottled Beyond',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 150,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-14-102408-1.png',
    precioVentaCrc: 54000,
    stockProveedor: true,
    notas: {
      salida: ['Jengibre', 'Notas cítricas'],
      corazon: ['Cuero', 'Acorde especiado'],
      fondo: ['Notas amaderadas', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-31',
    nombre: "L'Homme",
    marcaId: 'ysl',
    marca: { id: 'ysl', nombre: 'Yves Saint Laurent' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-16-101211-247x247.png',
    precioVentaCrc: 61500,
    stockProveedor: true,
    notas: {
      salida: ['Naranja amarga', 'Bergamota'],
      corazon: ['Vetiver', 'Lavanda', 'Geranio'],
      fondo: ['Madera de roble', 'Cedro'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-32',
    nombre: 'The Most Wanted (Tester)',
    marcaId: 'azzaro',
    marca: { id: 'azzaro', nombre: 'Azzaro' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Parfum',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    descripcion: 'Viene sin caja de lujo (tester). Es el mismo perfume original.',
    imagenUrl: null,
    precioVentaCrc: 40000,
    stockProveedor: true,
    notas: {
      salida: ['Jengibre rojo', 'Cardamomo'],
      corazon: ['Maderas incandescentes', 'Caramelo'],
      fondo: ['Vainilla Bourbon', 'Vetiver'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-33',
    nombre: 'Uomo Born In Roma Purple Melancholia',
    marcaId: 'valentino',
    marca: { id: 'valentino', nombre: 'Valentino' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/Captura-de-pantalla-2026-09-11-173652-247x247.jpg',
    precioVentaCrc: 64000,
    stockProveedor: true,
    notas: {
      salida: ['Cardamomo', 'Pimienta'],
      corazon: ['Lavanda', 'Coco cremoso'],
      fondo: ['Maderas ambaradas', 'Cedro'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-35',
    nombre: 'Light Blue Hombre',
    marcaId: 'dolce-gabbana',
    marca: { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 125,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 33000,
    stockProveedor: true,
    notas: {
      salida: ['Toronja', 'Bergamota', 'Mandarina siciliana', 'Enebro'],
      corazon: ['Pimienta', 'Romero', 'Palo de rosa'],
      fondo: ['Almizcle', 'Incienso', 'Musgo de roble'],
    },
    duracion: 3,
    proyeccion: 2,
  },
  {
    id: 'p-36',
    nombre: 'In Motion',
    marcaId: 'hugo-boss',
    marca: { id: 'hugo-boss', nombre: 'Hugo Boss' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/737052852034.jpg',
    precioVentaCrc: 16500,
    stockProveedor: true,
    notas: {
      salida: ['Naranja', 'Albahaca', 'Hojas de violeta', 'Bergamota'],
      corazon: ['Nuez moscada', 'Canela', 'Pimienta rosa', 'Cardamomo'],
      fondo: ['Sándalo', 'Vetiver', 'Notas amaderadas', 'Almizcle'],
    },
    duracion: 3,
    proyeccion: 3,
  },
  {
    id: 'p-37',
    nombre: 'Club De Nuit Intense',
    marcaId: 'armaf',
    marca: { id: 'armaf', nombre: 'Armaf' },
    clasificacion: 'Arabe',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 105,
    familiaOlfativa: 'Amaderado',
    imagenUrl: null,
    precioVentaCrc: 17000,
    stockProveedor: true,
    notas: {
      salida: ['Limón', 'Piña', 'Grosellas negras', 'Bergamota', 'Manzana'],
      corazon: ['Abedul', 'Jazmín', 'Rosa'],
      fondo: ['Almizcle', 'Ámbar gris', 'Pachulí', 'Vainilla'],
    },
    duracion: 5,
    proyeccion: 5,
  },
  {
    id: 'p-38',
    nombre: '9 PM Hombre',
    marcaId: 'afnan',
    marca: { id: 'afnan', nombre: 'Afnan' },
    clasificacion: 'Arabe',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Oriental',
    imagenUrl: null,
    precioVentaCrc: 14500,
    stockProveedor: true,
    notas: {
      salida: ['Manzana', 'Canela', 'Lavanda silvestre', 'Bergamota'],
      corazon: ['Flor de azahar del naranjo', 'Lirio de los valles'],
      fondo: ['Vainilla', 'Haba tonka', 'Ámbar', 'Pachulí'],
    },
    duracion: 5,
    proyeccion: 4,
  },
  {
    id: 'p-39',
    nombre: '360 Red',
    marcaId: 'perry-ellis',
    marca: { id: 'perry-ellis', nombre: 'Perry Ellis' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Amaderado',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/844061000551.jpg',
    precioVentaCrc: 14500,
    stockProveedor: true,
    notas: {
      salida: ['Lima', 'Bergamota', 'Canela', 'Nuez moscada', 'Mandarina'],
      corazon: ['Lavanda', 'Cilantro'],
      fondo: ['Almizcle', 'Pachulí', 'Sándalo', 'Cedro rojo', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 3,
  },
  {
    id: 'p-40',
    nombre: 'Blue',
    marcaId: 'nautica',
    marca: { id: 'nautica', nombre: 'Nautica' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Acuático',
    imagenUrl: 'https://catalogoperfumes.com/wp-content/uploads/2026/09/3412242508027-247x247.jpg',
    precioVentaCrc: 8500,
    stockProveedor: true,
    notas: {
      salida: ['Piña', 'Bergamota', 'Durazno'],
      corazon: ['Lirio de agua', 'Jazmín'],
      fondo: ['Sándalo', 'Cedro', 'Almizcle'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-41',
    nombre: 'Curve Chill Hombre',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Colonia',
    volumenMl: 125,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    notas: {
      salida: ['Aldehídos', 'Lima', 'Bergamota'],
      corazon: ['Té verde', 'Violeta', 'Pimienta blanca'],
      fondo: ['Sándalo', 'Almizcle', 'Vetiver', 'Cardamomo'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-42',
    nombre: 'Toy Boy',
    marcaId: 'moschino',
    marca: { id: 'moschino', nombre: 'Moschino' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDP',
    volumenMl: 100,
    familiaOlfativa: 'Gourmand',
    imagenUrl: null,
    precioVentaCrc: 28000,
    stockProveedor: true,
    notas: {
      salida: ['Pimienta rosa', 'Pera', 'Nuez moscada', 'Bergamota'],
      corazon: ['Rosa', 'Clavo de olor', 'Magnolia'],
      fondo: ['Madera de cachemira', 'Vetiver', 'Sándalo', 'Ámbar'],
    },
    duracion: 4,
    proyeccion: 4,
  },
  {
    id: 'p-43',
    nombre: 'Curve Connect Hombre',
    marcaId: 'liz-claiborne',
    marca: { id: 'liz-claiborne', nombre: 'Liz Claiborne' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'Colonia',
    volumenMl: 125,
    familiaOlfativa: 'Fresco',
    imagenUrl: null,
    precioVentaCrc: 10000,
    stockProveedor: true,
    notas: {
      salida: ['Ciruela', 'Melón blanco', 'Flor de cactus'],
      corazon: ['Azafrán', 'Canela'],
      fondo: ['Sándalo', 'Pachulí', 'Vainilla', 'Ámbar'],
    },
    duracion: 2,
    proyeccion: 2,
  },
  {
    id: 'p-44',
    nombre: '212 Tradicional Hombre',
    marcaId: 'carolina-herrera',
    marca: { id: 'carolina-herrera', nombre: 'Carolina Herrera' },
    clasificacion: 'Diseñador',
    genero: 'Masculino',
    concentracion: 'EDT',
    volumenMl: 100,
    familiaOlfativa: 'Citrico',
    imagenUrl: null,
    precioVentaCrc: 35500,
    stockProveedor: true,
    notas: {
      salida: ['Notas verdes', 'Toronja', 'Bergamota', 'Lavanda'],
      corazon: ['Jengibre', 'Violeta', 'Gardenia', 'Salvia'],
      fondo: ['Almizcle', 'Sándalo', 'Incienso', 'Vetiver'],
    },
    duracion: 4,
    proyeccion: 3,
  },
];

export const PERFUMES_SIMULADOS = CATALOGO_PERFUMES;

export function obtenerPerfumePorId(id: string): Perfume | undefined {
  return CATALOGO_PERFUMES.find((p) => p.id === id);
}
